/**
 * PHASE 13: SDK GENERATOR
 * 
 * Takes an OpenAPI v3 specification and dynamically generates a 
 * zero-dependency TypeScript SDK for it.
 */

export class SdkGenerator {
  
  /**
   * Translates OpenAPI JSON into a usable TypeScript API Client.
   */
  public generateTypeScript(openApiSpec: any): string {
    const title = openApiSpec?.info?.title?.replace(/[^a-zA-Z0-9]/g, '') || 'ApiClient';
    const baseUrl = openApiSpec?.servers?.[0]?.url || 'https://api.example.com';
    const paths = openApiSpec?.paths || {};

    let classBody = '';

    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods as Record<string, any>)) {
        // Convert /users/{id} to getUsersById
        const operationId = operation.operationId || this.generateMethodName(method, path);
        
        classBody += `
  /**
   * ${operation.summary || 'Execute ' + method.toUpperCase() + ' ' + path}
   */
  public async ${operationId}(params?: Record<string, any>): Promise<any> {
    const url = new URL(\`\${this.baseUrl}${path.replace(/\{([^}]+)\}/g, '$\\{params?.$1\\}')}\`);
    
    // Append query params if it's a GET request
    if (params && "${method.toUpperCase()}" === "GET") {
      Object.keys(params).forEach(key => url.searchParams.append(key, params[key]));
    }

    const response = await fetch(url.toString(), {
      method: '${method.toUpperCase()}',
      headers: {
        'Content-Type': 'application/json',
        ...this.headers
      },
      body: "${method.toUpperCase()}" !== "GET" && params ? JSON.stringify(params) : undefined
    });

    if (!response.ok) {
      throw new Error(\`API Error: \${response.statusText}\`);
    }

    return response.json();
  }
`;
      }
    }

    return `
// GENERATED BY MAHI API VERSE SDK BUILDER
// Target: ${title}
// Version: ${openApiSpec?.info?.version || '1.0.0'}

export class ${title} {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(apiKey?: string, baseUrl: string = '${baseUrl}') {
    this.baseUrl = baseUrl;
    this.headers = apiKey ? { 'Authorization': \`Bearer \${apiKey}\` } : {};
  }
${classBody}
}
`.trim();
  }

  /**
   * Helper to convert paths to method names if operationId is missing
   * Example: GET /users/profile -> getUsersProfile
   */
  private generateMethodName(method: string, path: string): string {
    const pathParts = path
      .replace(/[\{\}]/g, '') // Remove braces
      .split('/')
      .filter(Boolean)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1));
    return method.toLowerCase() + pathParts.join('');
  }
}
