import * as fs from 'fs-extra';
import * as path from 'path';
import * as Handlebars from 'handlebars';

const CATALOG_DIR = path.resolve(__dirname, '../../../catalog');

const API_TEMPLATE = `
# {{name}}
> {{description}}

**Provider:** {{provider}}
**Lifecycle Status:** {{lifecycle}}
**Last Verified:** {{lastVerified}}

## Intelligence Data
- **Canonical ID:** \`{{canonicalId}}\`
- **Endpoints Indexed:** {{endpointCount}}
- **SDKs Available:** {{sdkCount}}

## Supported Protocols
{{#each protocols}}
- **{{this.name}}** (\`{{this.version}}\`)
{{/each}}

## Endpoints
| Method | Path | Summary |
|---|---|---|
{{#each endpoints}}
| \`{{this.method}}\` | \`{{this.path}}\` | {{this.summary}} |
{{/each}}

## Language SDKs
| Language | Ecosystem | Support Tier | Package |
|---|---|---|---|
{{#each sdks}}
| **{{this.language}}** | {{this.ecosystem}} | {{this.tier}} | \`{{this.package}}\` |
{{/each}}

---
*Auto-generated by the Mahi API Verse Intelligence Engine.*
`;

async function generateCatalog() {
  console.log('📚 Starting GitHub Native Catalog Generation...');
  
  // 1. Ensure Catalog directory exists
  await fs.ensureDir(CATALOG_DIR);

  // 2. Compile Template
  const template = Handlebars.compile(API_TEMPLATE.trim());

  // 3. Mock Data Fetch (In production, this streams directly from Drizzle ORM)
  const mockApis = [
    {
      canonicalId: 'api_stripe_core',
      name: 'Stripe API',
      description: 'The Stripe API allows you to build billing and payment infrastructure.',
      provider: 'Stripe, Inc.',
      lifecycle: 'VERIFIED (Production)',
      lastVerified: new Date().toISOString(),
      endpointCount: 342,
      sdkCount: 7,
      protocols: [
        { name: 'REST', version: 'OpenAPI 3.0.0' }
      ],
      endpoints: [
        { method: 'POST', path: '/v1/charges', summary: 'Create a charge' },
        { method: 'GET', path: '/v1/customers', summary: 'List customers' }
      ],
      sdks: [
        { language: 'Node.js', ecosystem: 'npm', tier: 'Official', package: 'stripe' },
        { language: 'Python', ecosystem: 'PyPI', tier: 'Official', package: 'stripe' },
        { language: 'Rust', ecosystem: 'Crates.io', tier: 'Community', package: 'async-stripe' }
      ]
    }
  ];

  // 4. Generate Markdown Files
  for (const api of mockApis) {
    const markdownContent = template(api);
    const fileName = `${api.canonicalId.replace('api_', '')}.md`;
    const filePath = path.join(CATALOG_DIR, fileName);
    
    await fs.writeFile(filePath, markdownContent, 'utf-8');
    console.log(`✅ Generated catalog entry: catalog/${fileName}`);
  }

  // 5. Generate Root INDEX.md
  const indexContent = `# Mahi API Verse Catalog\n\nBrowse the fully generated API definitions natively in GitHub:\n\n${mockApis.map(a => `- [${a.name}](./${a.canonicalId.replace('api_', '')}.md)`).join('\n')}\n`;
  await fs.writeFile(path.join(CATALOG_DIR, 'INDEX.md'), indexContent, 'utf-8');
  
  console.log('🎉 Catalog Generation Complete.');
}

generateCatalog().catch(console.error);
