import * as fs from 'fs-extra';
import * as path from 'path';
import * as Handlebars from 'handlebars';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
// But let's keep it simple and just use the actual schema file if we can, or we will query via raw if types are hard.

const CATALOG_DIR = path.resolve(process.cwd(), 'catalog');

const API_TEMPLATE = `
# {{name}}
> {{description}}

**Provider:** {{provider}}
**Lifecycle Status:** {{lifecycle}}
**Last Verified:** {{lastVerified}}

## Intelligence Data
- **Canonical ID:** \`{{canonicalId}}\`
- **Endpoints Indexed:** {{endpointCount}}
- **SDKs Available:** {{sdkCount}}

## Supported Protocols
{{#each protocols}}
- **{{this.name}}** (\`{{this.version}}\`)
{{/each}}

## Endpoints
| Method | Path | Summary |
|---|---|---|
{{#each endpoints}}
| \`{{this.method}}\` | \`{{this.path}}\` | {{this.summary}} |
{{/each}}

## Language SDKs
| Language | Ecosystem | Support Tier | Package |
|---|---|---|---|
{{#each sdks}}
| **{{this.language}}** | {{this.ecosystem}} | {{this.tier}} | \`{{this.package}}\` |
{{/each}}

---
*Auto-generated by the Mahi API Verse Intelligence Engine.*
`;

async function generateCatalog() {
  console.log('📚 Starting GitHub Native Catalog Generation...');
  await fs.ensureDir(CATALOG_DIR);

  const template = Handlebars.compile(API_TEMPLATE.trim());

  let apiList: any[] = [];

  if (process.env.DATABASE_URL) {
    console.log('🔗 Fetching APIs from Drizzle ORM...');
    const pool = new Pool({ connectionString: process.env.DATABASE_URL });
    const db = drizzle(pool);
    // In a real scenario, we would do a complex join across tables.
    // We will do a generic mock for the demo.
    apiList = [];
    await pool.end();
  } else {
    console.log('⚠️ No DATABASE_URL found. Using Discovery Engine mock data...');
    apiList = [
      {
        canonicalId: 'api_stripe_core',
        name: 'Stripe API',
        description: 'The Stripe API allows you to build billing and payment infrastructure.',
        provider: 'Stripe, Inc.',
        lifecycle: 'VERIFIED (Production)',
        lastVerified: new Date().toISOString(),
        endpointCount: 342,
        sdkCount: 7,
        protocols: [
          { name: 'REST', version: 'OpenAPI 3.0.0' }
        ],
        endpoints: [
          { method: 'POST', path: '/v1/charges', summary: 'Create a charge' },
          { method: 'GET', path: '/v1/customers', summary: 'List customers' }
        ],
        sdks: [
          { language: 'Node.js', ecosystem: 'npm', tier: 'Official', package: 'stripe' },
          { language: 'Python', ecosystem: 'PyPI', tier: 'Official', package: 'stripe' },
          { language: 'Rust', ecosystem: 'Crates.io', tier: 'Community', package: 'async-stripe' }
        ]
      },
      {
        canonicalId: 'api_twilio_messaging',
        name: 'Twilio Programmable Messaging',
        description: 'Send and receive SMS and MMS on phone numbers around the world.',
        provider: 'Twilio',
        lifecycle: 'VERIFIED (Production)',
        lastVerified: new Date().toISOString(),
        endpointCount: 45,
        sdkCount: 5,
        protocols: [
          { name: 'REST', version: 'OpenAPI 3.1.0' }
        ],
        endpoints: [
          { method: 'POST', path: '/2010-04-01/Accounts/{AccountSid}/Messages.json', summary: 'Send a Message' }
        ],
        sdks: [
          { language: 'Node.js', ecosystem: 'npm', tier: 'Official', package: 'twilio' },
          { language: 'Python', ecosystem: 'PyPI', tier: 'Official', package: 'twilio' }
        ]
      }
    ];
  }

  for (const api of apiList) {
    const markdownContent = template(api);
    const fileName = `${api.canonicalId.replace('api_', '')}.md`;
    const filePath = path.join(CATALOG_DIR, fileName);
    
    await fs.writeFile(filePath, markdownContent, 'utf-8');
    console.log(`✅ Generated catalog entry: catalog/${fileName}`);
  }

  const indexContent = `# Mahi API Verse Catalog\n\nBrowse the fully generated API definitions natively in GitHub:\n\n${apiList.map(a => `- [${a.name}](./${a.canonicalId.replace('api_', '')}.md)`).join('\n')}\n`;
  await fs.writeFile(path.join(CATALOG_DIR, 'INDEX.md'), indexContent, 'utf-8');
  
  console.log('🎉 Catalog Generation Complete.');
}

generateCatalog().catch(console.error);
