import * as fs from 'fs-extra';
import * as path from 'path';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { apis, endpoints } from '@mahi-api-verse/database/src/schema';
import { eq } from 'drizzle-orm';
import { ApiDocumentationGenerator } from '@mahi-api-verse/api-documentation';

const CATALOG_DIR = path.resolve(process.cwd(), 'catalog');

const API_TEMPLATE = `
# {{name}}
> {{description}}

**Provider:** {{provider}}
**Lifecycle Status:** {{lifecycle}}
**Last Verified:** {{lastVerified}}

## Intelligence Data
- **Canonical ID:** \`{{canonicalId}}\`
- **Endpoints Indexed:** {{endpointCount}}
- **SDKs Available:** {{sdkCount}}

## Supported Protocols
{{#each protocols}}
- **{{this.name}}** (\`{{this.version}}\`)
{{/each}}

## Endpoints
| Method | Path | Summary |
|---|---|---|
{{#each endpoints}}
| \`{{this.method}}\` | \`{{this.path}}\` | {{this.summary}} |
{{/each}}

## Language SDKs
| Language | Ecosystem | Support Tier | Package |
|---|---|---|---|
{{#each sdks}}
| **{{this.language}}** | {{this.ecosystem}} | {{this.tier}} | \`{{this.package}}\` |
{{/each}}

---
*Auto-generated by the Mahi API Verse Intelligence Engine.*
`;

async function generateCatalog() {
  console.log('📚 Starting GitHub Native Catalog Generation...');
  await fs.ensureDir(CATALOG_DIR);

  if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL is required to generate real documentation.');
    process.exit(1);
  }

  console.log('🔗 Fetching APIs from Drizzle ORM...');
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);
  
  const allApis = await db.select().from(apis as any);
  console.log(`Found ${allApis.length} APIs in the intelligence database.`);

  const indexLinks: string[] = [];

  for (const record of allApis) {
    const apiRecord = record as any;
    console.log(`Generating docs for ${apiRecord.name}...`);
    
    // Fetch related endpoints
    const endpointRecords = await db.select().from(endpoints as any).where(eq(endpoints.apiId as any, apiRecord.id));
    const apiEndpoints = endpointRecords as any[];
    
    // Build Passport
    const passport = {
      id: apiRecord.id,
      name: apiRecord.name,
      state: apiRecord.lifecycle,
      baseUrls: [apiRecord.sourceUrl || `https://api.example.com`],
      endpoints: apiEndpoints.map(e => ({
        method: e.method,
        path: e.path,
        name: e.summary || undefined,
        description: e.summary || undefined,
        parameters: e.parameters ? (e.parameters as any) : [],
        requestBodySchema: e.requestSchema ? (e.requestSchema as any) : undefined,
        responses: e.responseSchema ? { '200': { schema: e.responseSchema } } : undefined
      }))
    };

    const bundle = await ApiDocumentationGenerator.generate(passport as any);
    
    let markdownContent = `---
title: "${apiRecord.name}"
description: "${apiRecord.description || 'API Documentation'}"
---

${bundle.overview}

${bundle.authentication}

## Endpoints

`;

    for (const [route, snippet] of Object.entries(bundle.endpoints)) {
      markdownContent += `${snippet}\n\n`;
    }

    markdownContent += `\n---\n*Auto-generated by Mahi API Verse Documentation Engine on ${new Date().toISOString()}*\n`;

    const fileName = `${apiRecord.slug}.mdx`;
    const filePath = path.join(CATALOG_DIR, fileName);
    await fs.writeFile(filePath, markdownContent, 'utf-8');
    console.log(`✅ Generated catalog entry: catalog/${fileName}`);
    
    indexLinks.push(`- [${apiRecord.name}](./${fileName})`);
  }

  const indexContent = `# Mahi API Verse Catalog\n\nBrowse the fully generated API definitions natively in GitHub:\n\n${indexLinks.join('\n')}\n`;
  await fs.writeFile(path.join(CATALOG_DIR, 'INDEX.md'), indexContent, 'utf-8');
  
  await pool.end();
  console.log('🎉 Catalog Generation Complete.');
}

generateCatalog().catch(console.error);
